name: rxn-insight
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - asttokens=2.0.5=pyhd3eb1b0_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - boost=1.74.0=py310hc781a3c_5
  - boost-cpp=1.74.0=h9f4b32c_8
  - brotli=1.1.0=hcfcfb64_1
  - brotli-bin=1.1.0=hcfcfb64_1
  - bzip2=1.0.8=hcfcfb64_5
  - ca-certificates=2023.11.17=h56e8100_0
  - cairo=1.16.0=he04af86_2
  - certifi=2023.11.17=pyhd8ed1ab_0
  - colorama=0.4.6=py310haa95532_0
  - cycler=0.12.1=pyhd8ed1ab_0
  - debugpy=1.6.7=py310hd77b12b_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - exceptiongroup=1.0.4=py310haa95532_0
  - executing=0.8.3=pyhd3eb1b0_0
  - fonttools=4.44.3=py310h8d17308_0
  - freetype=2.10.4=h546665d_2
  - gettext=0.21.1=h5728263_0
  - glib=2.78.1=h12be248_1
  - glib-tools=2.78.1=h12be248_1
  - greenlet=3.0.1=py310h00ffb61_0
  - intel-openmp=2023.2.0=h57928b3_50497
  - ipykernel=6.25.0=py310h9909e9c_0
  - ipython=8.15.0=py310haa95532_0
  - jedi=0.18.1=py310haa95532_1
  - jpeg=9e=hcfcfb64_3
  - jupyter_client=8.6.0=py310haa95532_0
  - jupyter_core=5.5.0=py310haa95532_0
  - kiwisolver=1.4.5=py310h232114e_1
  - lerc=3.0=hd77b12b_0
  - libblas=3.9.0=19_win64_mkl
  - libbrotlicommon=1.1.0=hcfcfb64_1
  - libbrotlidec=1.1.0=hcfcfb64_1
  - libbrotlienc=1.1.0=hcfcfb64_1
  - libcblas=3.9.0=19_win64_mkl
  - libdeflate=1.17=h2bbff1b_1
  - libffi=3.4.2=h8ffe710_5
  - libglib=2.78.1=h16e383f_1
  - libhwloc=2.9.3=default_haede6df_1009
  - libiconv=1.17=h8ffe710_0
  - liblapack=3.9.0=19_win64_mkl
  - libpng=1.6.39=h19919ed_0
  - libsodium=1.0.18=h62dcd97_0
  - libsqlite=3.44.0=hcfcfb64_0
  - libtiff=4.5.1=hd77b12b_0
  - libwebp=1.3.2=hcfcfb64_1
  - libwebp-base=1.3.2=hcfcfb64_0
  - libxml2=2.11.6=hc3477c8_0
  - libzlib=1.2.13=hcfcfb64_5
  - matplotlib-base=3.5.3=py310h79a7439_0
  - matplotlib-inline=0.1.6=py310haa95532_0
  - mkl=2023.2.0=h6a75c08_50496
  - munkres=1.1.4=pyh9f0ad1d_0
  - nest-asyncio=1.5.6=py310haa95532_0
  - numpy=1.26.0=py310hf667824_0
  - openjpeg=2.5.0=ha2aaf27_2
  - openssl=3.1.4=hcfcfb64_0
  - packaging=23.2=pyhd8ed1ab_0
  - pandas=2.1.3=py310hecd3228_0
  - parso=0.8.3=pyhd3eb1b0_0
  - pcre2=10.42=h17e33f8_0
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pillow=10.0.1=py310h045eedc_0
  - pip=23.3.1=pyhd8ed1ab_0
  - pixman=0.42.2=h63175ca_0
  - platformdirs=3.10.0=py310haa95532_0
  - prompt-toolkit=3.0.36=py310haa95532_0
  - psutil=5.9.0=py310h2bbff1b_0
  - pthreads-win32=2.9.1=hfa6e2cd_3
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - pycairo=1.23.0=py310had253c0_0
  - pygments=2.15.1=py310haa95532_1
  - pyparsing=3.1.1=pyhd8ed1ab_0
  - python=3.10.13=h4de0772_0_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python-tzdata=2023.3=pyhd8ed1ab_0
  - python_abi=3.10=4_cp310
  - pytz=2023.3.post1=pyhd8ed1ab_0
  - pywin32=305=py310h2bbff1b_0
  - pyzmq=25.1.0=py310hd77b12b_0
  - rdkit=2022.03.5=py310hc4884e0_0
  - reportlab=3.6.12=py310h2bbff1b_0
  - rust=1.74.0=hf8d6059_0
  - rust-std-x86_64-pc-windows-msvc=1.74.0=h17fc481_0
  - setuptools=68.2.2=pyhd8ed1ab_0
  - six=1.16.0=pyh6c4a22f_0
  - sqlalchemy=2.0.23=py310h8d17308_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - tbb=2021.10.0=h91493d7_2
  - tk=8.6.13=h5226925_1
  - tornado=6.3.3=py310h2bbff1b_0
  - traitlets=5.7.1=py310haa95532_0
  - typing-extensions=4.8.0=hd8ed1ab_0
  - typing_extensions=4.8.0=pyha770c72_0
  - tzdata=2023c=h71feb2d_0
  - ucrt=10.0.22621.0=h57928b3_0
  - unicodedata2=15.1.0=py310h8d17308_0
  - vc=14.3=h64f974e_17
  - vc14_runtime=14.36.32532=hdcecf7f_17
  - vs2015_runtime=14.36.32532=h05e6639_17
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - wheel=0.41.3=pyhd8ed1ab_0
  - xz=5.4.2=h8cc25b3_0
  - zeromq=4.3.4=hd77b12b_0
  - zlib=1.2.13=hcfcfb64_5
  - zstd=1.5.5=h12be248_0
  - pip:
      - annotated-types==0.6.0
      - attrs==23.1.0
      - charset-normalizer==3.3.2
      - click==8.1.7
      - comm==0.2.0
      - cramjam==2.7.0
      - diskcache==5.6.3
      - dnspython==2.4.2
      - fastparquet==2023.10.1
      - filelock==3.13.1
      - fsspec==2023.10.0
      - huggingface-hub==0.19.4
      - idna==3.4
      - ipywidgets==8.1.1
      - jinja2==3.1.2
      - jupyterlab-widgets==3.0.9
      - markupsafe==2.1.3
      - mpmath==1.3.0
      - networkx==3.2.1
      - pyarrow==13.0.0
      - pydantic==2.5.1
      - pydantic-core==2.14.3
      - pymongo==4.6.0
      - pyyaml==6.0.1
      - rdchiral==1.1.0
      - regex==2023.10.3
      - requests==2.31.0
      - rxn-chem-utils==1.4.0
      - rxn-utils==1.6.0
      - rxnmapper==0.2.9
      - safetensors==0.4.0
      - scipy==1.11.4
      - sympy==1.12
      - tokenizers==0.15.0
      - torch==2.0.1
      - tqdm==4.66.1
      - transformers==4.35.2
      - urllib3==2.1.0
      - widgetsnbextension==4.0.9
